### PR TITLE
feat(gatsbyjs/gatsby): add initial yaml file validation PR rule

### PR DESCRIPTION
**Pull request by pieh**
this adds initial yaml file validation - there are initial schemas for:
- docs/sites.yml (site showcase)
- docs/community/creators.yml (creator showcase)
- docs/starters.yml (starter showcase)
- docs/blog/author.yaml (blog posts authors metadata)

It currently verify that:
- yaml files are valid (probably not needed, as we do linting anyway)
- there are no unknown fields used
- required fields are filled (need to actually verify what fields are required)
- image fields (authors, creators) link to existing file (file need to exist in PR branch) and that file uses supported extension

What it **doesn't** do:
- check if files are actually images
- verify that urls work (return 200 status) - few roadblocks here:
  - `joi` schemas I used don't support async validators (but this can be workarounded with some not nice extra handling - like I did when checking of image fields pointing to existing files) 
  - currently it validates whole yaml file and not just things that changed, so checking >200 sites would slow this thing down. We still would need to validate whole yaml at least to check uniqueness of some of fields, but trying out if url is alive could be done just for urls that changed

I was using testing that against my custom repo, that has same yaml files and same places as gatsbyjs/gatsby repo - https://github.com/pieh/peril-testing - check open PRs for how it works (mostly "checks" tab) and feel free to open new PRs there to test correctness (just remember I run this locally so peril might not always be up)

TO-DOs
- add tests
  - [x] site showcase
  - [x] creator showcase
  - [x] starter showcase
  - [x] blog posts authors metadata
- [x] validate if schemas are actually correct (required fields)
- [x] don't use `fail` for initial rollout and use `message` while verifying correctness of validation
- [ ] fix entries in gatsbyjs/gatsby that don't pass validation (but they should)

Questions:
- ~~how additional dependencies are actually added to heroku instance running peril? I was deving locally so I needed to install them in my local peril instance, but this seemed weird?~~
- edit: can I split rule file? tried splitting it out so utils would be in other files, but importling local modules doesn't seem to work (peril app says it can't find those)

### CODE REVIEW

**Comment by LeKoArts** [comment]
You might also want to add a check whether all tags are capitalized or not:
https://github.com/gatsbyjs/gatsby/pull/8693

**Comment by jlengstorf** [comment]
@pieh for the extra dependencies, we need to add them to the "modules" field of the peril settings.

For reference, here's the Peril source with some explanation of how it works: https://github.com/danger/peril/blob/772aa0089f42122d9f299e698a14072405f82980/source/db/GitHubRepoSettings.ts#L2-L8

You may want to try that locally first, because you're the first person to build something complex enough to need external dependencies. 😄

**Comment by pieh** [comment]
I've checked `modules` setting for extra dependency and this works, but it does require to run `yarn setup` before `yarn start` - I'm not sure if this is happening or how to force it

This is almost good to go - last thing to do is fix [sites.yml](https://github.com/pieh/peril-testing/pull/5/checks) and [starters.yml](https://github.com/pieh/peril-testing/pull/12/checks) in gatsbyjs/gatsby - they don't pass validation that we agreed on

Opportunities for further development of validation are (I don't want to add this in initial version to not overcomplicate this PR - let's see how this will work before adding more features):
 - warn if entry adds completely new category (sites.yml) or tag (starters.yml) - it can be completely valid new category, but we also don't want to end up with very niche categories that has just single entries. Also if new category/tag would be added try to match it to existing one in case of use typo error and warn "did you mean X?"
- warn if someone tries to set featured flag / category (sites.yml) - only `ecosystem`/`docs` team should be able to do that

**Comment by jlengstorf** [comment]
@pieh Do we need to fix the `sites.yml` and `starters.yml` _before_ merging this?

**Comment by jlengstorf** [comment]
Also: do we have the output of a validation run with the existing errors so someone can go through and make fixes? I can potentially take a run at that this week to get it done.

**Comment by pieh** [comment]
https://github.com/pieh/peril-testing/pull/5/checks and https://github.com/pieh/peril-testing/pull/12/checks are outputs of running validation against almost current yaml files (~3 days old)

**Pull request merged**
